spring.application.name=doc-queue
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=${DB_USERNAME}&prepareThreshold=0

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# ? Add this line to release database connections instantly after a query runs
spring.jpa.open-in-view=false

# ? Increase the maximum number of simultaneous database connections
spring.datasource.hikari.maximum-pool-size=20

# ? Reduce the maximum time a request will wait for a connection before failing (from 30s to 5s)
spring.datasource.hikari.connection-timeout=5000

# ? Maximum time a connection can sit completely idle before being recycled
spring.datasource.hikari.idle-timeout=600000